/// Cross-language interoperability tests using fixtures generated by
/// Python's msgpack library. Verifies wire-format compatibility by
/// decoding binary fixtures and comparing against expected values,
/// then re-encoding and comparing bytes (round-trip).
import gleam/bit_array
import gleam/dict.{type Dict}
import gleam/dynamic.{type Dynamic}
import gleam/dynamic/decode
import gleam/int
import gleam/json
import gleam/list
import gleam/string
import gleam/time/timestamp
import msgpack_gleam.{pack, unpack, unpack_exact}
import msgpack_gleam/timestamp as msgpack_timestamp
import msgpack_gleam/value.{
  Array, Binary, Boolean, Float, Integer, Map, Nil, String,
}
import simplifile
import startest
import startest/expect
import test_helpers

pub fn main() {
  startest.run(startest.default_config())
}

const interop_dir = "test/test_data/interop/"

// ============================================================================
// Helpers
// ============================================================================

fn load_fixture(filename: String) -> BitArray {
  let path = interop_dir <> filename
  let assert Ok(data) = simplifile.read_bits(path)
  data
}

fn load_manifest() -> Dict(String, Dynamic) {
  let assert Ok(content) = simplifile.read(interop_dir <> "manifest.json")
  let assert Ok(manifest) =
    json.parse(content, decode.dict(decode.string, decode.dynamic))
  manifest
}

fn get_fixtures(
  manifest: Dict(String, Dynamic),
  category: String,
) -> List(Dict(String, Dynamic)) {
  let assert Ok(fixtures_dyn) = dict.get(manifest, "fixtures")
  let assert Ok(categories) =
    decode.run(fixtures_dyn, decode.dict(decode.string, decode.dynamic))
  let assert Ok(cat_dyn) = dict.get(categories, category)
  let assert Ok(fixtures) =
    decode.run(cat_dyn, decode.list(decode.dict(decode.string, decode.dynamic)))
  fixtures
}

fn get_string_field(fixture: Dict(String, Dynamic), key: String) -> String {
  let assert Ok(v) = dict.get(fixture, key)
  let assert Ok(s) = decode.run(v, decode.string)
  s
}

/// Find a map entry by key using equality comparison
fn find_entry(
  entries: List(#(value.Value, value.Value)),
  key: value.Value,
) -> value.Value {
  let assert Ok(#(_, v)) =
    list.find(entries, fn(pair) {
      let #(k, _) = pair
      k == key
    })
  v
}

// ============================================================================
// Integer Boundary Tests
// ============================================================================

pub fn interop_integer_boundaries_test() {
  let manifest = load_manifest()
  let fixtures = get_fixtures(manifest, "integer-boundaries")

  list.each(fixtures, fn(fixture) {
    let filename = get_string_field(fixture, "file")
    let description = get_string_field(fixture, "description")
    let data = load_fixture(filename)

    let expected = case dict.get(fixture, "number") {
      Ok(v) -> {
        let assert Ok(n) = decode.run(v, decode.int)
        n
      }
      Error(_) -> {
        let assert Ok(v) = dict.get(fixture, "bignum")
        let assert Ok(s) = decode.run(v, decode.string)
        let assert Ok(n) = int.parse(s)
        n
      }
    }

    // Decode the fixture
    let result = unpack_exact(data)
    case result {
      Ok(Integer(n)) -> {
        case n == expected {
          True -> Nil
          False ->
            panic as {
              "Integer mismatch for "
              <> description
              <> ": expected "
              <> int.to_string(expected)
              <> ", got "
              <> int.to_string(n)
            }
        }
      }
      Ok(other) ->
        panic as {
          "Expected Integer for "
          <> description
          <> ", got "
          <> value.type_name(other)
        }
      Error(e) ->
        panic as {
          "Decode failed for " <> description <> ": " <> string.inspect(e)
        }
    }

    // Round-trip: re-encode and compare bytes
    let assert Ok(re_encoded) = pack(Integer(expected))
    case re_encoded == data {
      True -> Nil
      False ->
        panic as {
          "Round-trip mismatch for "
          <> description
          <> ": original="
          <> test_helpers.bits_to_hex(data)
          <> ", re-encoded="
          <> test_helpers.bits_to_hex(re_encoded)
        }
    }
  })
}

// ============================================================================
// Nested Structure Tests
// ============================================================================

pub fn interop_nested_map_array_map_test() {
  let data = load_fixture("nested_map_array_map.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  let expected =
    Map([
      #(
        String("users"),
        Array([
          Map([
            #(String("name"), String("Alice")),
            #(String("scores"), Array([Integer(95), Integer(87), Integer(92)])),
          ]),
          Map([
            #(String("name"), String("Bob")),
            #(String("scores"), Array([Integer(88), Integer(91), Integer(85)])),
          ]),
        ]),
      ),
    ])

  decoded |> expect.to_equal(expected)

  // Round-trip
  let assert Ok(re_encoded) = pack(expected)
  let assert Ok(re_decoded) = unpack_exact(re_encoded)
  re_decoded |> expect.to_equal(expected)
}

pub fn interop_nested_3d_array_test() {
  let data = load_fixture("nested_3d_array.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  let expected =
    Array([
      Array([
        Array([Integer(1), Integer(2)]),
        Array([Integer(3), Integer(4)]),
      ]),
      Array([
        Array([Integer(5), Integer(6)]),
        Array([Integer(7), Integer(8)]),
      ]),
    ])

  decoded |> expect.to_equal(expected)

  // Round-trip
  let assert Ok(re_encoded) = pack(expected)
  re_encoded |> expect.to_equal(data)
}

pub fn interop_nested_deep_maps_test() {
  let data = load_fixture("nested_deep_maps.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  let expected =
    Map([
      #(
        String("a"),
        Map([
          #(
            String("b"),
            Map([#(String("c"), Map([#(String("d"), String("deep"))]))]),
          ),
        ]),
      ),
    ])

  decoded |> expect.to_equal(expected)

  let assert Ok(re_encoded) = pack(expected)
  re_encoded |> expect.to_equal(data)
}

pub fn interop_nested_empty_test() {
  let data = load_fixture("nested_empty.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  // {"empty_array": [], "empty_map": {}, "nested_empty": {"inner": []}}
  let assert Map(entries) = decoded
  list.length(entries) |> expect.to_equal(3)

  // Use find_entry helper (equality-based lookup) instead of dict/let assert
  find_entry(entries, String("empty_array")) |> expect.to_equal(Array([]))
  find_entry(entries, String("empty_map")) |> expect.to_equal(Map([]))

  let assert Map(inner_entries) = find_entry(entries, String("nested_empty"))
  find_entry(inner_entries, String("inner")) |> expect.to_equal(Array([]))
}

// ============================================================================
// Large Data Tests
// ============================================================================

pub fn interop_large_string_str8_test() {
  let data = load_fixture("large_string_200.msgpack")
  unpack_exact(data) |> expect.to_equal(Ok(String(string.repeat("A", 200))))

  // Round-trip
  let assert Ok(re_encoded) = pack(String(string.repeat("A", 200)))
  re_encoded |> expect.to_equal(data)
}

pub fn interop_large_string_str16_test() {
  let data = load_fixture("large_string_300.msgpack")
  unpack_exact(data) |> expect.to_equal(Ok(String(string.repeat("B", 300))))

  let assert Ok(re_encoded) = pack(String(string.repeat("B", 300)))
  re_encoded |> expect.to_equal(data)
}

pub fn interop_large_string_str32_test() {
  let data = load_fixture("large_string_70k.msgpack")
  unpack_exact(data) |> expect.to_equal(Ok(String(string.repeat("C", 70_000))))

  let assert Ok(re_encoded) = pack(String(string.repeat("C", 70_000)))
  re_encoded |> expect.to_equal(data)
}

pub fn interop_large_binary_bin8_test() {
  let data = load_fixture("large_binary_200.msgpack")
  let assert Ok(Binary(b)) = unpack_exact(data)
  bit_array.byte_size(b) |> expect.to_equal(200)

  let assert Ok(re_encoded) = pack(Binary(b))
  re_encoded |> expect.to_equal(data)
}

pub fn interop_large_binary_bin16_test() {
  let data = load_fixture("large_binary_500.msgpack")
  let assert Ok(Binary(b)) = unpack_exact(data)
  bit_array.byte_size(b) |> expect.to_equal(500)

  let assert Ok(re_encoded) = pack(Binary(b))
  re_encoded |> expect.to_equal(data)
}

// ============================================================================
// Mixed-Type Tests
// ============================================================================

pub fn interop_mixed_array_test() {
  let data = load_fixture("mixed_array.msgpack")
  let assert Ok(Array(items)) = unpack_exact(data)

  // [nil, true, false, 42, -1, 3.14, "hello", binary(0xdead), [1,2], {"a":1}]
  list.length(items) |> expect.to_equal(10)

  // Verify each element with expect.to_equal
  let assert [v0, v1, v2, v3, v4, v5, v6, v7, v8, v9] = items
  v0 |> expect.to_equal(Nil)
  v1 |> expect.to_equal(Boolean(True))
  v2 |> expect.to_equal(Boolean(False))
  v3 |> expect.to_equal(Integer(42))
  v4 |> expect.to_equal(Integer(-1))
  // Float: check it decoded to Float type, then compare value
  let assert Float(f) = v5
  let assert True = float_close(f, 3.14, 0.0001)
  v6 |> expect.to_equal(String("hello"))
  v7 |> expect.to_equal(Binary(<<0xde, 0xad>>))
  v8 |> expect.to_equal(Array([Integer(1), Integer(2)]))
  v9 |> expect.to_equal(Map([#(String("a"), Integer(1))]))
}

pub fn interop_int_key_map_test() {
  let data = load_fixture("mixed_int_key_map.msgpack")
  let assert Ok(Map(entries)) = unpack_exact(data)

  // {1: "one", 2: "two", 3: "three"}
  let expected = [
    #(Integer(1), String("one")),
    #(Integer(2), String("two")),
    #(Integer(3), String("three")),
  ]
  entries |> expect.to_equal(expected)
}

pub fn interop_mixed_key_map_test() {
  let data = load_fixture("mixed_key_map.msgpack")
  let assert Ok(Map(entries)) = unpack_exact(data)

  // {true: "bool_key", "str": "string_key", 42: "int_key"}
  list.length(entries) |> expect.to_equal(3)

  find_entry(entries, Boolean(True)) |> expect.to_equal(String("bool_key"))
  find_entry(entries, String("str")) |> expect.to_equal(String("string_key"))
  find_entry(entries, Integer(42)) |> expect.to_equal(String("int_key"))
}

// ============================================================================
// Timestamp Tests
// ============================================================================

pub fn interop_timestamp32_test() {
  let data = load_fixture("timestamp32.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  let assert Ok(ts) = msgpack_timestamp.decode(decoded)
  let #(seconds, nanoseconds) = timestamp.to_unix_seconds_and_nanoseconds(ts)
  seconds |> expect.to_equal(1_234_567_890)
  nanoseconds |> expect.to_equal(0)

  // Round-trip
  let re_encoded_value = msgpack_timestamp.encode(ts)
  let assert Ok(re_encoded_bytes) = pack(re_encoded_value)
  re_encoded_bytes |> expect.to_equal(data)
}

pub fn interop_timestamp64_test() {
  let data = load_fixture("timestamp64.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  let assert Ok(ts) = msgpack_timestamp.decode(decoded)
  let #(seconds, nanoseconds) = timestamp.to_unix_seconds_and_nanoseconds(ts)
  seconds |> expect.to_equal(1_234_567_890)
  nanoseconds |> expect.to_equal(500_000_000)

  let re_encoded_value = msgpack_timestamp.encode(ts)
  let assert Ok(re_encoded_bytes) = pack(re_encoded_value)
  re_encoded_bytes |> expect.to_equal(data)
}

pub fn interop_timestamp96_test() {
  let data = load_fixture("timestamp96.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  let assert Ok(ts) = msgpack_timestamp.decode(decoded)
  let #(seconds, nanoseconds) = timestamp.to_unix_seconds_and_nanoseconds(ts)
  seconds |> expect.to_equal(253_402_300_799)
  nanoseconds |> expect.to_equal(999_999_999)

  let re_encoded_value = msgpack_timestamp.encode(ts)
  let assert Ok(re_encoded_bytes) = pack(re_encoded_value)
  re_encoded_bytes |> expect.to_equal(data)
}

pub fn interop_timestamp_epoch_test() {
  let data = load_fixture("timestamp_epoch.msgpack")
  let assert Ok(decoded) = unpack_exact(data)

  let assert Ok(ts) = msgpack_timestamp.decode(decoded)
  let #(seconds, nanoseconds) = timestamp.to_unix_seconds_and_nanoseconds(ts)
  seconds |> expect.to_equal(0)
  nanoseconds |> expect.to_equal(0)

  let re_encoded_value = msgpack_timestamp.encode(ts)
  let assert Ok(re_encoded_bytes) = pack(re_encoded_value)
  re_encoded_bytes |> expect.to_equal(data)
}

// ============================================================================
// Streaming Decode Tests (multiple concatenated values)
// ============================================================================

pub fn interop_stream_three_values_test() {
  let data = load_fixture("stream_three_values.msgpack")

  // Decode first value: Integer(42)
  let assert Ok(#(v1, rest1)) = unpack(data)
  v1 |> expect.to_equal(Integer(42))

  // Decode second value: String("hello")
  let assert Ok(#(v2, rest2)) = unpack(rest1)
  v2 |> expect.to_equal(String("hello"))

  // Decode third value: Boolean(True)
  let assert Ok(#(v3, rest3)) = unpack(rest2)
  v3 |> expect.to_equal(Boolean(True))

  // No remaining bytes
  bit_array.byte_size(rest3) |> expect.to_equal(0)
}

pub fn interop_stream_five_values_test() {
  let data = load_fixture("stream_five_values.msgpack")

  let assert Ok(#(v1, rest1)) = unpack(data)
  v1 |> expect.to_equal(Nil)

  let assert Ok(#(v2, rest2)) = unpack(rest1)
  v2 |> expect.to_equal(Integer(255))

  let assert Ok(#(v3, rest3)) = unpack(rest2)
  v3 |> expect.to_equal(String("test"))

  let assert Ok(#(v4, rest4)) = unpack(rest3)
  v4 |> expect.to_equal(Array([Integer(1), Integer(2), Integer(3)]))

  let assert Ok(#(v5, rest5)) = unpack(rest4)
  v5 |> expect.to_equal(Map([#(String("key"), String("val"))]))

  // No remaining bytes
  bit_array.byte_size(rest5) |> expect.to_equal(0)
}

// ============================================================================
// Cross-implementation round-trip: encode in Gleam, verify bytes match Python
// ============================================================================

pub fn interop_roundtrip_all_integers_test() {
  let manifest = load_manifest()
  let fixtures = get_fixtures(manifest, "integer-boundaries")

  list.each(fixtures, fn(fixture) {
    let filename = get_string_field(fixture, "file")
    let expected_hex = get_string_field(fixture, "msgpack_hex")
    let reference_bytes = load_fixture(filename)

    let expected = case dict.get(fixture, "number") {
      Ok(v) -> {
        let assert Ok(n) = decode.run(v, decode.int)
        n
      }
      Error(_) -> {
        let assert Ok(v) = dict.get(fixture, "bignum")
        let assert Ok(s) = decode.run(v, decode.string)
        let assert Ok(n) = int.parse(s)
        n
      }
    }

    // Encode with Gleam
    let assert Ok(gleam_bytes) = pack(Integer(expected))

    // Compare hex representations for better error messages
    let gleam_hex = test_helpers.bits_to_hex(gleam_bytes)
    case gleam_hex == expected_hex {
      True -> Nil
      False ->
        panic as {
          "Encoding mismatch for "
          <> filename
          <> ": python="
          <> expected_hex
          <> ", gleam="
          <> gleam_hex
        }
    }

    gleam_bytes |> expect.to_equal(reference_bytes)
  })
}

// ============================================================================
// Helpers
// ============================================================================

fn float_close(a: Float, b: Float, tolerance: Float) -> Bool {
  let diff = case a -. b {
    d if d <. 0.0 -> 0.0 -. d
    d -> d
  }
  diff <. tolerance
}
